version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            npm run build
            - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

  say-hello-workflow:
    jobs:
      - say-hello
